/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as PortalTransfersRouteImport } from './routes/portal/transfers'
import { Route as PortalSupportRouteImport } from './routes/portal/support'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalNotificationsRouteImport } from './routes/portal/notifications'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalLoansRouteImport } from './routes/portal/loans'
import { Route as PortalInvestmentsRouteImport } from './routes/portal/investments'
import { Route as PortalAiAssistantRouteImport } from './routes/portal/ai-assistant'
import { Route as PortalAccountsRouteImport } from './routes/portal/accounts'
import { Route as JoinRegisterRouteImport } from './routes/join/register'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTransfersRoute = PortalTransfersRouteImport.update({
  id: '/portal/transfers',
  path: '/portal/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/portal/support',
  path: '/portal/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/portal/notifications',
  path: '/portal/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoansRoute = PortalLoansRouteImport.update({
  id: '/portal/loans',
  path: '/portal/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInvestmentsRoute = PortalInvestmentsRouteImport.update({
  id: '/portal/investments',
  path: '/portal/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAiAssistantRoute = PortalAiAssistantRouteImport.update({
  id: '/portal/ai-assistant',
  path: '/portal/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAccountsRoute = PortalAccountsRouteImport.update({
  id: '/portal/accounts',
  path: '/portal/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRegisterRoute = JoinRegisterRouteImport.update({
  id: '/join/register',
  path: '/join/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRoute
  '/tenders': typeof TendersRoute
  '/join/register': typeof JoinRegisterRoute
  '/portal/accounts': typeof PortalAccountsRoute
  '/portal/ai-assistant': typeof PortalAiAssistantRoute
  '/portal/investments': typeof PortalInvestmentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transfers': typeof PortalTransfersRoute
  '/join/': typeof JoinIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRoute
  '/tenders': typeof TendersRoute
  '/join/register': typeof JoinRegisterRoute
  '/portal/accounts': typeof PortalAccountsRoute
  '/portal/ai-assistant': typeof PortalAiAssistantRoute
  '/portal/investments': typeof PortalInvestmentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transfers': typeof PortalTransfersRoute
  '/join': typeof JoinIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/media': typeof MediaRoute
  '/products': typeof ProductsRoute
  '/tenders': typeof TendersRoute
  '/join/register': typeof JoinRegisterRoute
  '/portal/accounts': typeof PortalAccountsRoute
  '/portal/ai-assistant': typeof PortalAiAssistantRoute
  '/portal/investments': typeof PortalInvestmentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transfers': typeof PortalTransfersRoute
  '/join/': typeof JoinIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faqs'
    | '/insurance'
    | '/loans'
    | '/media'
    | '/products'
    | '/tenders'
    | '/join/register'
    | '/portal/accounts'
    | '/portal/ai-assistant'
    | '/portal/investments'
    | '/portal/loans'
    | '/portal/login'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transfers'
    | '/join/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faqs'
    | '/insurance'
    | '/loans'
    | '/media'
    | '/products'
    | '/tenders'
    | '/join/register'
    | '/portal/accounts'
    | '/portal/ai-assistant'
    | '/portal/investments'
    | '/portal/loans'
    | '/portal/login'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transfers'
    | '/join'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faqs'
    | '/insurance'
    | '/loans'
    | '/media'
    | '/products'
    | '/tenders'
    | '/join/register'
    | '/portal/accounts'
    | '/portal/ai-assistant'
    | '/portal/investments'
    | '/portal/loans'
    | '/portal/login'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transfers'
    | '/join/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  InsuranceRoute: typeof InsuranceRoute
  LoansRoute: typeof LoansRoute
  MediaRoute: typeof MediaRoute
  ProductsRoute: typeof ProductsRoute
  TendersRoute: typeof TendersRoute
  JoinRegisterRoute: typeof JoinRegisterRoute
  PortalAccountsRoute: typeof PortalAccountsRoute
  PortalAiAssistantRoute: typeof PortalAiAssistantRoute
  PortalInvestmentsRoute: typeof PortalInvestmentsRoute
  PortalLoansRoute: typeof PortalLoansRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTransfersRoute: typeof PortalTransfersRoute
  JoinIndexRoute: typeof JoinIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/transfers': {
      id: '/portal/transfers'
      path: '/portal/transfers'
      fullPath: '/portal/transfers'
      preLoaderRoute: typeof PortalTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/portal/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/portal/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/loans': {
      id: '/portal/loans'
      path: '/portal/loans'
      fullPath: '/portal/loans'
      preLoaderRoute: typeof PortalLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/investments': {
      id: '/portal/investments'
      path: '/portal/investments'
      fullPath: '/portal/investments'
      preLoaderRoute: typeof PortalInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/ai-assistant': {
      id: '/portal/ai-assistant'
      path: '/portal/ai-assistant'
      fullPath: '/portal/ai-assistant'
      preLoaderRoute: typeof PortalAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/accounts': {
      id: '/portal/accounts'
      path: '/portal/accounts'
      fullPath: '/portal/accounts'
      preLoaderRoute: typeof PortalAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/register': {
      id: '/join/register'
      path: '/join/register'
      fullPath: '/join/register'
      preLoaderRoute: typeof JoinRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  InsuranceRoute: InsuranceRoute,
  LoansRoute: LoansRoute,
  MediaRoute: MediaRoute,
  ProductsRoute: ProductsRoute,
  TendersRoute: TendersRoute,
  JoinRegisterRoute: JoinRegisterRoute,
  PortalAccountsRoute: PortalAccountsRoute,
  PortalAiAssistantRoute: PortalAiAssistantRoute,
  PortalInvestmentsRoute: PortalInvestmentsRoute,
  PortalLoansRoute: PortalLoansRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTransfersRoute: PortalTransfersRoute,
  JoinIndexRoute: JoinIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
