/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InsuranceProductsRouteImport } from './routes/insurance-products'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as ResourcesTendersRouteImport } from './routes/resources/tenders'
import { Route as ResourcesNewsRouteImport } from './routes/resources/news'
import { Route as ResourcesMarketplaceRouteImport } from './routes/resources/marketplace'
import { Route as ResourcesFormsRouteImport } from './routes/resources/forms'
import { Route as ResourcesCareersRouteImport } from './routes/resources/careers'
import { Route as ResourcesCalculatorRouteImport } from './routes/resources/calculator'
import { Route as ProductsIslamicFinanceRouteImport } from './routes/products/islamic-finance'
import { Route as ProductsFosaSavingsRouteImport } from './routes/products/fosa-savings'
import { Route as ProductsFosaLoansRouteImport } from './routes/products/fosa-loans'
import { Route as ProductsFinancialServicesRouteImport } from './routes/products/financial-services'
import { Route as ProductsDepositsRouteImport } from './routes/products/deposits'
import { Route as ProductsBosaLoansRouteImport } from './routes/products/bosa-loans'
import { Route as PortalTransfersRouteImport } from './routes/portal/transfers'
import { Route as PortalSupportRouteImport } from './routes/portal/support'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalNotificationsRouteImport } from './routes/portal/notifications'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalLoansRouteImport } from './routes/portal/loans'
import { Route as PortalInvestmentsRouteImport } from './routes/portal/investments'
import { Route as PortalBuySellSharesRouteImport } from './routes/portal/buy-sell-shares'
import { Route as PortalAiAssistantRouteImport } from './routes/portal/ai-assistant'
import { Route as PortalAccountsRouteImport } from './routes/portal/accounts'
import { Route as JoinRegisterRouteImport } from './routes/join/register'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceProductsRoute = InsuranceProductsRouteImport.update({
  id: '/insurance-products',
  path: '/insurance-products',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTendersRoute = ResourcesTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesNewsRoute = ResourcesNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesMarketplaceRoute = ResourcesMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesFormsRoute = ResourcesFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesCareersRoute = ResourcesCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesCalculatorRoute = ResourcesCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProductsIslamicFinanceRoute = ProductsIslamicFinanceRouteImport.update({
  id: '/islamic-finance',
  path: '/islamic-finance',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsFosaSavingsRoute = ProductsFosaSavingsRouteImport.update({
  id: '/fosa-savings',
  path: '/fosa-savings',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsFosaLoansRoute = ProductsFosaLoansRouteImport.update({
  id: '/fosa-loans',
  path: '/fosa-loans',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsFinancialServicesRoute =
  ProductsFinancialServicesRouteImport.update({
    id: '/financial-services',
    path: '/financial-services',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsDepositsRoute = ProductsDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBosaLoansRoute = ProductsBosaLoansRouteImport.update({
  id: '/bosa-loans',
  path: '/bosa-loans',
  getParentRoute: () => ProductsRoute,
} as any)
const PortalTransfersRoute = PortalTransfersRouteImport.update({
  id: '/portal/transfers',
  path: '/portal/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/portal/support',
  path: '/portal/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/portal/notifications',
  path: '/portal/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoansRoute = PortalLoansRouteImport.update({
  id: '/portal/loans',
  path: '/portal/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInvestmentsRoute = PortalInvestmentsRouteImport.update({
  id: '/portal/investments',
  path: '/portal/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBuySellSharesRoute = PortalBuySellSharesRouteImport.update({
  id: '/portal/buy-sell-shares',
  path: '/portal/buy-sell-shares',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAiAssistantRoute = PortalAiAssistantRouteImport.update({
  id: '/portal/ai-assistant',
  path: '/portal/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAccountsRoute = PortalAccountsRouteImport.update({
  id: '/portal/accounts',
  path: '/portal/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRegisterRoute = JoinRegisterRouteImport.update({
  id: '/join/register',
  path: '/join/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/insurance': typeof InsuranceRoute
  '/insurance-products': typeof InsuranceProductsRoute
  '/leadership': typeof LeadershipRoute
  '/loans': typeof LoansRoute
  '/media': typeof MediaRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/tenders': typeof TendersRoute
  '/join/register': typeof JoinRegisterRoute
  '/portal/accounts': typeof PortalAccountsRoute
  '/portal/ai-assistant': typeof PortalAiAssistantRoute
  '/portal/buy-sell-shares': typeof PortalBuySellSharesRoute
  '/portal/investments': typeof PortalInvestmentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transfers': typeof PortalTransfersRoute
  '/products/bosa-loans': typeof ProductsBosaLoansRoute
  '/products/deposits': typeof ProductsDepositsRoute
  '/products/financial-services': typeof ProductsFinancialServicesRoute
  '/products/fosa-loans': typeof ProductsFosaLoansRoute
  '/products/fosa-savings': typeof ProductsFosaSavingsRoute
  '/products/islamic-finance': typeof ProductsIslamicFinanceRoute
  '/resources/calculator': typeof ResourcesCalculatorRoute
  '/resources/careers': typeof ResourcesCareersRoute
  '/resources/forms': typeof ResourcesFormsRoute
  '/resources/marketplace': typeof ResourcesMarketplaceRoute
  '/resources/news': typeof ResourcesNewsRoute
  '/resources/tenders': typeof ResourcesTendersRoute
  '/join/': typeof JoinIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/insurance': typeof InsuranceRoute
  '/insurance-products': typeof InsuranceProductsRoute
  '/leadership': typeof LeadershipRoute
  '/loans': typeof LoansRoute
  '/media': typeof MediaRoute
  '/our-story': typeof OurStoryRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/tenders': typeof TendersRoute
  '/join/register': typeof JoinRegisterRoute
  '/portal/accounts': typeof PortalAccountsRoute
  '/portal/ai-assistant': typeof PortalAiAssistantRoute
  '/portal/buy-sell-shares': typeof PortalBuySellSharesRoute
  '/portal/investments': typeof PortalInvestmentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transfers': typeof PortalTransfersRoute
  '/products/bosa-loans': typeof ProductsBosaLoansRoute
  '/products/deposits': typeof ProductsDepositsRoute
  '/products/financial-services': typeof ProductsFinancialServicesRoute
  '/products/fosa-loans': typeof ProductsFosaLoansRoute
  '/products/fosa-savings': typeof ProductsFosaSavingsRoute
  '/products/islamic-finance': typeof ProductsIslamicFinanceRoute
  '/resources/calculator': typeof ResourcesCalculatorRoute
  '/resources/careers': typeof ResourcesCareersRoute
  '/resources/forms': typeof ResourcesFormsRoute
  '/resources/marketplace': typeof ResourcesMarketplaceRoute
  '/resources/news': typeof ResourcesNewsRoute
  '/resources/tenders': typeof ResourcesTendersRoute
  '/join': typeof JoinIndexRoute
  '/portal': typeof PortalIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/insurance': typeof InsuranceRoute
  '/insurance-products': typeof InsuranceProductsRoute
  '/leadership': typeof LeadershipRoute
  '/loans': typeof LoansRoute
  '/media': typeof MediaRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/tenders': typeof TendersRoute
  '/join/register': typeof JoinRegisterRoute
  '/portal/accounts': typeof PortalAccountsRoute
  '/portal/ai-assistant': typeof PortalAiAssistantRoute
  '/portal/buy-sell-shares': typeof PortalBuySellSharesRoute
  '/portal/investments': typeof PortalInvestmentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transfers': typeof PortalTransfersRoute
  '/products/bosa-loans': typeof ProductsBosaLoansRoute
  '/products/deposits': typeof ProductsDepositsRoute
  '/products/financial-services': typeof ProductsFinancialServicesRoute
  '/products/fosa-loans': typeof ProductsFosaLoansRoute
  '/products/fosa-savings': typeof ProductsFosaSavingsRoute
  '/products/islamic-finance': typeof ProductsIslamicFinanceRoute
  '/resources/calculator': typeof ResourcesCalculatorRoute
  '/resources/careers': typeof ResourcesCareersRoute
  '/resources/forms': typeof ResourcesFormsRoute
  '/resources/marketplace': typeof ResourcesMarketplaceRoute
  '/resources/news': typeof ResourcesNewsRoute
  '/resources/tenders': typeof ResourcesTendersRoute
  '/join/': typeof JoinIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faqs'
    | '/insurance'
    | '/insurance-products'
    | '/leadership'
    | '/loans'
    | '/media'
    | '/our-story'
    | '/products'
    | '/resources'
    | '/tenders'
    | '/join/register'
    | '/portal/accounts'
    | '/portal/ai-assistant'
    | '/portal/buy-sell-shares'
    | '/portal/investments'
    | '/portal/loans'
    | '/portal/login'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transfers'
    | '/products/bosa-loans'
    | '/products/deposits'
    | '/products/financial-services'
    | '/products/fosa-loans'
    | '/products/fosa-savings'
    | '/products/islamic-finance'
    | '/resources/calculator'
    | '/resources/careers'
    | '/resources/forms'
    | '/resources/marketplace'
    | '/resources/news'
    | '/resources/tenders'
    | '/join/'
    | '/portal/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faqs'
    | '/insurance'
    | '/insurance-products'
    | '/leadership'
    | '/loans'
    | '/media'
    | '/our-story'
    | '/resources'
    | '/tenders'
    | '/join/register'
    | '/portal/accounts'
    | '/portal/ai-assistant'
    | '/portal/buy-sell-shares'
    | '/portal/investments'
    | '/portal/loans'
    | '/portal/login'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transfers'
    | '/products/bosa-loans'
    | '/products/deposits'
    | '/products/financial-services'
    | '/products/fosa-loans'
    | '/products/fosa-savings'
    | '/products/islamic-finance'
    | '/resources/calculator'
    | '/resources/careers'
    | '/resources/forms'
    | '/resources/marketplace'
    | '/resources/news'
    | '/resources/tenders'
    | '/join'
    | '/portal'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faqs'
    | '/insurance'
    | '/insurance-products'
    | '/leadership'
    | '/loans'
    | '/media'
    | '/our-story'
    | '/products'
    | '/resources'
    | '/tenders'
    | '/join/register'
    | '/portal/accounts'
    | '/portal/ai-assistant'
    | '/portal/buy-sell-shares'
    | '/portal/investments'
    | '/portal/loans'
    | '/portal/login'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transfers'
    | '/products/bosa-loans'
    | '/products/deposits'
    | '/products/financial-services'
    | '/products/fosa-loans'
    | '/products/fosa-savings'
    | '/products/islamic-finance'
    | '/resources/calculator'
    | '/resources/careers'
    | '/resources/forms'
    | '/resources/marketplace'
    | '/resources/news'
    | '/resources/tenders'
    | '/join/'
    | '/portal/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  InsuranceRoute: typeof InsuranceRoute
  InsuranceProductsRoute: typeof InsuranceProductsRoute
  LeadershipRoute: typeof LeadershipRoute
  LoansRoute: typeof LoansRoute
  MediaRoute: typeof MediaRoute
  OurStoryRoute: typeof OurStoryRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  TendersRoute: typeof TendersRoute
  JoinRegisterRoute: typeof JoinRegisterRoute
  PortalAccountsRoute: typeof PortalAccountsRoute
  PortalAiAssistantRoute: typeof PortalAiAssistantRoute
  PortalBuySellSharesRoute: typeof PortalBuySellSharesRoute
  PortalInvestmentsRoute: typeof PortalInvestmentsRoute
  PortalLoansRoute: typeof PortalLoansRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTransfersRoute: typeof PortalTransfersRoute
  JoinIndexRoute: typeof JoinIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-products': {
      id: '/insurance-products'
      path: '/insurance-products'
      fullPath: '/insurance-products'
      preLoaderRoute: typeof InsuranceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/tenders': {
      id: '/resources/tenders'
      path: '/tenders'
      fullPath: '/resources/tenders'
      preLoaderRoute: typeof ResourcesTendersRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/news': {
      id: '/resources/news'
      path: '/news'
      fullPath: '/resources/news'
      preLoaderRoute: typeof ResourcesNewsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/marketplace': {
      id: '/resources/marketplace'
      path: '/marketplace'
      fullPath: '/resources/marketplace'
      preLoaderRoute: typeof ResourcesMarketplaceRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/forms': {
      id: '/resources/forms'
      path: '/forms'
      fullPath: '/resources/forms'
      preLoaderRoute: typeof ResourcesFormsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/careers': {
      id: '/resources/careers'
      path: '/careers'
      fullPath: '/resources/careers'
      preLoaderRoute: typeof ResourcesCareersRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/calculator': {
      id: '/resources/calculator'
      path: '/calculator'
      fullPath: '/resources/calculator'
      preLoaderRoute: typeof ResourcesCalculatorRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/products/islamic-finance': {
      id: '/products/islamic-finance'
      path: '/islamic-finance'
      fullPath: '/products/islamic-finance'
      preLoaderRoute: typeof ProductsIslamicFinanceRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/fosa-savings': {
      id: '/products/fosa-savings'
      path: '/fosa-savings'
      fullPath: '/products/fosa-savings'
      preLoaderRoute: typeof ProductsFosaSavingsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/fosa-loans': {
      id: '/products/fosa-loans'
      path: '/fosa-loans'
      fullPath: '/products/fosa-loans'
      preLoaderRoute: typeof ProductsFosaLoansRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/financial-services': {
      id: '/products/financial-services'
      path: '/financial-services'
      fullPath: '/products/financial-services'
      preLoaderRoute: typeof ProductsFinancialServicesRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/deposits': {
      id: '/products/deposits'
      path: '/deposits'
      fullPath: '/products/deposits'
      preLoaderRoute: typeof ProductsDepositsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/bosa-loans': {
      id: '/products/bosa-loans'
      path: '/bosa-loans'
      fullPath: '/products/bosa-loans'
      preLoaderRoute: typeof ProductsBosaLoansRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/portal/transfers': {
      id: '/portal/transfers'
      path: '/portal/transfers'
      fullPath: '/portal/transfers'
      preLoaderRoute: typeof PortalTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/portal/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/portal/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/loans': {
      id: '/portal/loans'
      path: '/portal/loans'
      fullPath: '/portal/loans'
      preLoaderRoute: typeof PortalLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/investments': {
      id: '/portal/investments'
      path: '/portal/investments'
      fullPath: '/portal/investments'
      preLoaderRoute: typeof PortalInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/buy-sell-shares': {
      id: '/portal/buy-sell-shares'
      path: '/portal/buy-sell-shares'
      fullPath: '/portal/buy-sell-shares'
      preLoaderRoute: typeof PortalBuySellSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/ai-assistant': {
      id: '/portal/ai-assistant'
      path: '/portal/ai-assistant'
      fullPath: '/portal/ai-assistant'
      preLoaderRoute: typeof PortalAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/accounts': {
      id: '/portal/accounts'
      path: '/portal/accounts'
      fullPath: '/portal/accounts'
      preLoaderRoute: typeof PortalAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/register': {
      id: '/join/register'
      path: '/join/register'
      fullPath: '/join/register'
      preLoaderRoute: typeof JoinRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsBosaLoansRoute: typeof ProductsBosaLoansRoute
  ProductsDepositsRoute: typeof ProductsDepositsRoute
  ProductsFinancialServicesRoute: typeof ProductsFinancialServicesRoute
  ProductsFosaLoansRoute: typeof ProductsFosaLoansRoute
  ProductsFosaSavingsRoute: typeof ProductsFosaSavingsRoute
  ProductsIslamicFinanceRoute: typeof ProductsIslamicFinanceRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBosaLoansRoute: ProductsBosaLoansRoute,
  ProductsDepositsRoute: ProductsDepositsRoute,
  ProductsFinancialServicesRoute: ProductsFinancialServicesRoute,
  ProductsFosaLoansRoute: ProductsFosaLoansRoute,
  ProductsFosaSavingsRoute: ProductsFosaSavingsRoute,
  ProductsIslamicFinanceRoute: ProductsIslamicFinanceRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesCalculatorRoute: typeof ResourcesCalculatorRoute
  ResourcesCareersRoute: typeof ResourcesCareersRoute
  ResourcesFormsRoute: typeof ResourcesFormsRoute
  ResourcesMarketplaceRoute: typeof ResourcesMarketplaceRoute
  ResourcesNewsRoute: typeof ResourcesNewsRoute
  ResourcesTendersRoute: typeof ResourcesTendersRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesCalculatorRoute: ResourcesCalculatorRoute,
  ResourcesCareersRoute: ResourcesCareersRoute,
  ResourcesFormsRoute: ResourcesFormsRoute,
  ResourcesMarketplaceRoute: ResourcesMarketplaceRoute,
  ResourcesNewsRoute: ResourcesNewsRoute,
  ResourcesTendersRoute: ResourcesTendersRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  InsuranceRoute: InsuranceRoute,
  InsuranceProductsRoute: InsuranceProductsRoute,
  LeadershipRoute: LeadershipRoute,
  LoansRoute: LoansRoute,
  MediaRoute: MediaRoute,
  OurStoryRoute: OurStoryRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  TendersRoute: TendersRoute,
  JoinRegisterRoute: JoinRegisterRoute,
  PortalAccountsRoute: PortalAccountsRoute,
  PortalAiAssistantRoute: PortalAiAssistantRoute,
  PortalBuySellSharesRoute: PortalBuySellSharesRoute,
  PortalInvestmentsRoute: PortalInvestmentsRoute,
  PortalLoansRoute: PortalLoansRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTransfersRoute: PortalTransfersRoute,
  JoinIndexRoute: JoinIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
